import React from 'react';
import PolicyLayout from '../components/PolicyLayout';

export default function PrivacyPolicy() {
  return (
    <PolicyLayout title="Privacy Policy" lastUpdated="15 March 2026">
      <div className="prose">
        <p>This Privacy Policy explains how Wardseal ("WardSeal", "we", "us", "our") collects, uses, shares, and protects personal data when providing the WardSeal identity and access platform.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>1. Scope</h2>
        <p>This Privacy Policy applies to:</p>
        <ul>
          <li>Public website and marketing pages</li>
          <li>WardSeal cloud services (including admin console and APIs)</li>
          <li>Customer support and account management interactions</li>
        </ul>
        <p>For self-hosted deployments, customers control hosting and infrastructure choices. This policy still applies to interactions with us directly (for example, support, billing, and account administration).</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>2. Roles</h2>
        <p>Depending on context, we may act as:</p>
        <ul>
          <li><strong>Controller</strong> for account, billing, and business contact data</li>
          <li><strong>Processor</strong> for customer-managed end-user identity data processed on behalf of customers</li>
        </ul>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>3. Data we collect</h2>
        <h3 style={{ color: '#fff', marginTop: '24px' }}>3.1 Data customers provide</h3>
        <ul>
          <li>Account profile information (name, work email, company)</li>
          <li>Contract and billing details</li>
          <li>Support requests and communications</li>
        </ul>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>3.2 Data processed in the service</h3>
        <p>WardSeal may process identity and authentication-related data, such as:</p>
        <ul>
          <li>User identifiers (for example email, username, user ID)</li>
          <li>Organization and tenant context</li>
          <li>Authentication events (login attempts, MFA events, token issuance events)</li>
          <li>Device and security telemetry used to secure authentication sessions</li>
          <li>Audit log metadata generated by administrative operations</li>
        </ul>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>3.3 Automatically collected data</h3>
        <ul>
          <li>Security and diagnostics logs</li>
          <li>Service usage metrics</li>
          <li>Technical metadata needed for availability, abuse prevention, and troubleshooting</li>
        </ul>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>4. How we use data</h2>
        <p>We use personal data to:</p>
        <ul>
          <li>Provide, secure, and improve WardSeal services</li>
          <li>Authenticate users and enforce access controls</li>
          <li>Detect and prevent fraud, abuse, and unauthorized access</li>
          <li>Provide customer support and AI-assisted diagnostics (via Security Copilot)</li>
          <li>Comply with legal obligations</li>
        </ul>
        <p><strong>AI Processing Notice:</strong> We process telemetry queries through Large Language Models to surface security insights. Data transmitted for parsing excludes primary underlying credentials.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>5. Legal bases (EEA/UK)</h2>
        <p>Where GDPR or UK GDPR applies, we rely on one or more legal bases:</p>
        <ul>
          <li>Performance of a contract</li>
          <li>Legitimate interests (for security, fraud prevention, and service improvement)</li>
          <li>Legal obligation</li>
          <li>Consent (where required)</li>
        </ul>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>India (DPDP Act, 2023)</h3>
        <p>Where India data protection law applies, WardSeal processes personal data for lawful purposes related to service delivery, security, fraud prevention, compliance, and customer-requested operations. Where consent is the basis, consent is requested through appropriate notices and can be withdrawn subject to legal and contractual limitations.</p>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>United States (state privacy law baseline)</h3>
        <p>Where applicable U.S. state privacy laws apply, we provide required notices and rights workflows, including access, correction, deletion, and portability, subject to statutory exceptions.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>6. Sharing and disclosure</h2>
        <p>We may share data with:</p>
        <ul>
          <li>Service providers/subprocessors that help operate the service</li>
          <li>Professional advisors (for example legal, audit)</li>
          <li>Authorities when legally required</li>
          <li>Parties involved in a corporate transaction (subject to safeguards)</li>
        </ul>
        <p>We do not sell personal data in exchange for monetary compensation.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>7. International transfers</h2>
        <p>If data is transferred across borders, we ensure compliance via European Commission Standard Contractual Clauses (SCCs), UK International Data Transfer Agreements, or explicit adequacy determinations.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>8. Data retention</h2>
        <p>We retain personal data for as long as needed to provide the service, meet contractual obligations, resolve disputes, and comply with law. Detailed retention periods are documented in our internal data retention policies.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>9. Security measures and breach notifications</h2>
        <p>We use technical and organizational measures designed to protect data, including access controls, encryption in transit, tenant isolation controls, and audit logging.</p>
        <p><strong>Breach Notification:</strong> In the event of a confirmed security incident involving Personal Data, WardSeal will notify affected administrators without undue delay and, where feasible, not later than 72 hours after discovery.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>10. Your rights</h2>
        <p>Depending on location, individuals may have rights to access personal data, correct inaccurate data, delete data, restrict or object to processing, data portability, and withdraw consent.</p>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>10.1 EU/EEA rights (GDPR)</h3>
        <p>Individuals may have rights to access, rectification, erasure, restriction, objection, portability, and complaint to a supervisory authority.</p>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>10.2 India rights (DPDP)</h3>
        <p>Data principals may have rights to access information about processing, correction and erasure, grievance redressal, and nomination rights, as applicable under law.</p>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>10.3 U.S. state privacy rights</h3>
        <p>Residents of certain U.S. states may have rights to know/access, correct, delete, and obtain copies of personal data, plus rights related to certain profiling and targeted advertising contexts where applicable.</p>

        <h3 style={{ color: '#fff', marginTop: '24px' }}>10.4 Verification and appeals</h3>
        <p>We may verify request identity before fulfilling rights requests. Where required by law, we provide a process to appeal request decisions.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>11. Cookies and tracking</h2>
        <p>Our use of cookies and similar technologies is described in our Cookie Policy.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>12. Children</h2>
        <p>WardSeal is intended for business and enterprise use and is not directed to children under 18 years of age.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>13. Changes to this policy</h2>
        <p>We may update this Privacy Policy from time to time. Material changes will be communicated via website notice, in-product notice, or by email when required.</p>

        <h2 style={{ color: '#fff', marginTop: '32px' }}>14. Contact</h2>
        <ul>
          <li>Privacy contact: <strong>privacy@wardseal.com</strong></li>
          <li>Data protection contact: <strong>dpo@wardseal.com</strong></li>
          <li>India grievance contact: <strong>privacy@wardseal.com</strong></li>
          <li>Postal address: Vapi, Gujarat</li>
        </ul>
      </div>
    </PolicyLayout>
  );
}
