apiVersion: v2
name: wardseal
description: Identity Platform - Umbrella Helm Chart
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: authsvc
    version: "0.1.0"
    repository: "file://../authsvc"
    condition: authsvc.enabled

  - name: dirsvc
    version: "0.1.0"
    repository: "file://../dirsvc"
    condition: dirsvc.enabled

  - name: govsvc
    version: "0.1.0"
    repository: "file://../govsvc"
    condition: govsvc.enabled

  - name: policysvc
    version: "0.1.0"
    repository: "file://../policysvc"
    condition: policysvc.enabled

  - name: provsvc
    version: "0.1.0"
    repository: "file://../provsvc"
    condition: provsvc.enabled

  - name: adminui
    version: "0.1.0"
    repository: "file://../adminui"
    condition: adminui.enabled

  - name: landingui
    version: "0.1.0"
    repository: "file://../landingui"
    condition: landingui.enabled
