apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wardseal-production-ingress
  namespace: argocd
  labels:
    environment: production
    service: ingress
spec:
  project: production
  source:
    repoURL: https://github.com/dhawalhost/wardseal.git
    targetRevision: main
    path: deploy/charts/wardseal
    helm:
      releaseName: wardseal
      valueFiles:
        - values.yaml
        - values-production.yaml
        - services/ingress/selector.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wardseal-production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
