replicaCount: 1

env:
  ENVIRONMENT: staging
  LOG_LEVEL: debug
  REDIS_ENABLED: "true"
  REDIS_ADDR: redis-staging.wardseal.svc.cluster.local:6379
  RATE_LIMIT_USE_TENANT: "true"
  RATE_LIMIT_KEY_PREFIX: wardseal:ratelimit
  CORS_ALLOWED_ORIGINS: https://staging.wardseal.com,https://manage-staging.wardseal.com

database:
  existingSecret: wardseal-db-credentials-staging
